spring:
  application:
    name: gateway
  banner:
    location: classpath:banner.txt

server:
  port: 8844
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true

app.eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.security.oauth2.resourceserver.jwt:
  issuer-uri: http://localhost:8080/realms/SazonRealm

management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

---
spring.config.activate.on-profile: docker

app.eureka-server: eureka-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

spring.security.oauth2.resourceserver.jwt:
  issuer-uri: http://host.docker.internal:8080/realms/SazonRealm

spring.cloud.config.uri: http://config-server:8888
