spring:
  application:
    name: ms-reservas

  config:
    import: optional:classpath:application-openapi.yml

  datasource:
    url: jdbc:postgresql://sazon-postgres:5432/SazonDB?serverTimezone=America/La_Paz
    username: alejandro
    password: '{cipher}53e99279f935de2e49b12637777b40e9d2d94bcf5238189b9b31f5f9e7c23661'
    hikari:
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: America/La_Paz
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    time-zone: America/La_Paz

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SazonRealm
          jwk-set-uri: http://host.docker.internal:8080/realms/SazonRealm/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

server:
  port: 7003
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    org.springframework: INFO
    "[org.springframework.web]": DEBUG
    "[org.hibernate]": ERROR
    "[com.example]": DEBUG

app:
  eureka-server: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
