spring:
  application:
    name: ms-usuarios
  config:
    import: optional:classpath:application-openapi.yml

  # Base de datos PostgreSQL (contenedor)
  datasource:
    url: jdbc:postgresql://localhost:5432/SazonDB
    username: alejandro
    password: "1234"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SazonRealm
          jwk-set-uri: http://host.docker.internal:8080/realms/SazonRealm/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

server:
  port: 7001

app:
  threadPoolSize: 10
  taskQueueSize: 100

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.ms_usuarios: DEBUG
    org.hibernate.SQL: DEBUG

# Propiedades necesarias para OpenAPI
api:
  common:
    version: "1.0"

# Spring Cloud Stream + RabbitMQ (contenedor)
spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings:
    messageProcessor-in-0:
      destination: usuarios
      group: usuariosGroup

  stream.rabbit.bindings.messageProcessor-in-0.consumer:
    maxAttempts: 3
    backOffInitialInterval: 500
    backOffMaxInterval: 1000
    backOffMultiplier: 2.0

spring.rabbitmq:
  host: rabbitmq
  port: 5672
  username: admin
  password: admin
